# Build steps for AWS CodeBuild.
version: 0.2
phases:
  build:
    commands:
      - ls -al
      - ls -al ${CODEBUILD_SRC_DIR_JSONContent}
      - npm -v
      - npm ci
      - node -v
      - node index.js
